[package]
name = "desktop-postflop"
version = "0.1.0"
authors = ["Wataru Inariba"]
edition = "2021"
rust-version = "1.57"
repository = "https://github.com/b-inary/desktop-postflop/tree/main/src-tauri"
license = "AGPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "1.0.1", features = [] }

[dependencies]
postflop-solver = { git = "https://github.com/b-inary/postflop-solver", features = ["custom-alloc"] }
rayon = "1.5.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
sysinfo = "0.24.5"
tauri = { version = "1.0.1", features = ["shell-open"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = "thin"
