[package]
name = "desktop-postflop"
version = "0.0.1"
authors = ["Wataru Inariba"]
license = "AGPL-3.0-or-later"
repository = ""
default-run = "desktop-postflop"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
postflop-solver = { git = "https://github.com/b-inary/postflop-solver", features = ["custom_alloc"] }
rayon = "1.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.24"
tauri = { version = "1.0.0", features = ["shell-open"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
lto = "thin"
