name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install app dependencies
        run: npm ci
      - name: Build the app
        run: npm run tauri build
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            src-tauri/target/release/Desktop Postflop.exe
            src-tauri/target/release/bundle/msi/Desktop Postflop_*_x64_en-US.msi
