name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Rust nightly
        uses: actions-rs/toolchain@v2
        with:
          toolchain: nightly
          components: rust-src
          default: true
      - name: Install app dependencies
        run: npm ci
      - name: Build the app
        run: npm run tauri build -- --target x86_64-pc-windows-msvc -- -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            src-tauri/target/x86_64-pc-windows-msvc/release/Desktop Postflop.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/Desktop Postflop_*_x64_en-US.msi
